// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CloseSession():Promise<Array<any>>;

export function DeleteGroupsById(arg1:Array<string>):Promise<Array<any>>;

export function DeleteItemsById(arg1:Array<string>):Promise<Array<any>>;

export function DeleteTwoFactorSecret():Promise<Array<any>>;

export function FocusWindow():Promise<void>;

export function GeneratePassword(arg1:database.Ruleset,arg2:Array<string>):Promise<Array<any>>;

export function GenerateTwoFactorSecret():Promise<Array<any>>;

export function GetDatabase():Promise<Array<any>>;

export function GetFaviconURL(arg1:string):Promise<Array<any>>;

export function HasStorage():Promise<Array<any>>;

export function HasTwoFactorAuthentication():Promise<Array<any>>;

export function InitializeStorage(arg1:string):Promise<Array<any>>;

export function InsertGroups(arg1:Array<database.Group>):Promise<Array<any>>;

export function InsertItems(arg1:Array<database.InsertItemsArg>):Promise<Array<any>>;

export function IsAuthenticated():Promise<Array<any>>;

export function LoadImage(arg1:string):Promise<Array<any>>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<Array<any>>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function ReadLoadedImage():Promise<Array<any>>;

export function UnlockLoadedImage(arg1:string):Promise<Array<any>>;

export function UpdateGroupsById(arg1:Array<database.GroupUpdate>):Promise<Array<any>>;

export function UpdateItemsById(arg1:Array<database.ItemUpdate>):Promise<Array<any>>;

export function ValidatePassword(arg1:string,arg2:database.Ruleset,arg3:Array<string>):Promise<Array<any>>;

export function ValidateTwoFactorCode(arg1:string,arg2:boolean):Promise<Array<any>>;

export function ValidateTwoFactorRecoveryCode(arg1:string):Promise<Array<any>>;
