// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfFallbackFavicon(arg1) {
  return window['go']['main']['App']['CheckIfFallbackFavicon'](arg1);
}

export function CloseSession() {
  return window['go']['main']['App']['CloseSession']();
}

export function DeleteGroupsById(arg1) {
  return window['go']['main']['App']['DeleteGroupsById'](arg1);
}

export function DeleteItemsById(arg1) {
  return window['go']['main']['App']['DeleteItemsById'](arg1);
}

export function DeleteTwoFactorSecret() {
  return window['go']['main']['App']['DeleteTwoFactorSecret']();
}

export function FocusWindow() {
  return window['go']['main']['App']['FocusWindow']();
}

export function GeneratePassword(arg1, arg2) {
  return window['go']['main']['App']['GeneratePassword'](arg1, arg2);
}

export function GenerateTwoFactorSecret() {
  return window['go']['main']['App']['GenerateTwoFactorSecret']();
}

export function GetDatabase() {
  return window['go']['main']['App']['GetDatabase']();
}

export function HasStorage() {
  return window['go']['main']['App']['HasStorage']();
}

export function HasTwoFactorAuthentication() {
  return window['go']['main']['App']['HasTwoFactorAuthentication']();
}

export function InitializeStorage(arg1) {
  return window['go']['main']['App']['InitializeStorage'](arg1);
}

export function InsertGroups(arg1) {
  return window['go']['main']['App']['InsertGroups'](arg1);
}

export function InsertItems(arg1) {
  return window['go']['main']['App']['InsertItems'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenURLInBrowser(arg1) {
  return window['go']['main']['App']['OpenURLInBrowser'](arg1);
}

export function ReadLoadedImage() {
  return window['go']['main']['App']['ReadLoadedImage']();
}

export function UnlockLoadedImage(arg1) {
  return window['go']['main']['App']['UnlockLoadedImage'](arg1);
}

export function UpdateGroupsById(arg1) {
  return window['go']['main']['App']['UpdateGroupsById'](arg1);
}

export function UpdateItemsById(arg1) {
  return window['go']['main']['App']['UpdateItemsById'](arg1);
}

export function ValidatePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidatePassword'](arg1, arg2, arg3);
}

export function ValidateTwoFactorCode(arg1, arg2) {
  return window['go']['main']['App']['ValidateTwoFactorCode'](arg1, arg2);
}

export function ValidateTwoFactorRecoveryCode(arg1) {
  return window['go']['main']['App']['ValidateTwoFactorRecoveryCode'](arg1);
}
